#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define ENERGEST_FREQ 100
#define IO_WIDTH 11
#define RF_CHANNEL 26

#define NETSTACK_CONF_RDC nullrdc_driver
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 16 
#define NETSTACK_CONF_MAC csma_driver
#define ENERGEST_CONF_ON 1

#define UART_CONF_ENABLE 0
#define UIP_CONF_ROUTER 0

//#define TCPIP_CONF_ANNOTATE_TRANSMISSIONS 1
#endif /* PROJECT_CONF_H_ */
