CONTIKI = ../..

ifndef TARGET
TARGET=z1
endif

all: black-receiver-unicast-etnew-maite black-receiver black-sender-energest \
	 white-sender-maite white-sink

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
